/**
 * AUTO-GENERATED by scripts/build-services-db.mjs — DO NOT EDIT MANUALLY.
 * Generated: 2026-06-11
 * Source: data/services.yaml (schemaVersion: 1)
 *
 * To regenerate: node scripts/build-services-db.mjs
 */
import type { ServiceDefinition } from './db.js'

// 50 hand-curated service definitions
export const CURATED_SERVICES: ServiceDefinition[] = [
  {
    id: "ga4",
    name: "Google Analytics 4",
    category: "analytics",
    cookies: [
      { name: "_ga", wildcard: false },
      { name: "_ga_", wildcard: true },
      { name: "_gali", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "google-analytics.com",
      "analytics.google.com",
      "googletagmanager.com",
    ],
    google: true,
    source: 'curated',
  },
  {
    id: "ua",
    name: "Google Universal Analytics (GA3)",
    category: "analytics",
    cookies: [
      { name: "_gid", wildcard: false },
      { name: "_gat", wildcard: true },
      { name: "_dc_gtm_", wildcard: true },
      { name: "__utma", wildcard: false },
      { name: "__utmb", wildcard: false },
      { name: "__utmc", wildcard: false },
      { name: "__utmt", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "google-analytics.com",
    ],
    google: true,
    source: 'curated',
  },
  {
    id: "gtm",
    name: "Google Tag Manager",
    category: "analytics",
    cookies: [
    ],
    localStorage: [
    ],
    requestHosts: [
      "googletagmanager.com",
    ],
    google: true,
    source: 'curated',
  },
  {
    id: "meta-pixel",
    name: "Meta (Facebook) Pixel",
    category: "marketing",
    cookies: [
      { name: "_fbp", wildcard: false },
      { name: "_fbc", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "connect.facebook.net",
    ],
    requestPaths: [
      "facebook.com/tr",
    ],
    source: 'curated',
  },
  {
    id: "youtube",
    name: "YouTube",
    category: "marketing",
    cookies: [
      { name: "VISITOR_INFO1_LIVE", wildcard: false },
      { name: "YSC", wildcard: false },
      { name: "PREF", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "youtube.com",
      "youtube-nocookie.com",
      "ytimg.com",
    ],
    source: 'curated',
  },
  {
    id: "linkedin-insight",
    name: "LinkedIn Insight Tag",
    category: "marketing",
    cookies: [
      { name: "lidc", wildcard: false },
      { name: "lissc", wildcard: false },
      { name: "li_gc", wildcard: false },
      { name: "AnalyticsSyncHistory", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "linkedin.com",
      "snap.licdn.com",
    ],
    source: 'curated',
  },
  {
    id: "hotjar",
    name: "Hotjar",
    category: "analytics",
    cookies: [
      { name: "_hjid", wildcard: false },
      { name: "_hjFirstSeen", wildcard: false },
      { name: "_hjIncludedInPageviewSample", wildcard: false },
      { name: "_hjSession", wildcard: true },
    ],
    localStorage: [
      { name: "_hjSessionId", wildcard: false },
    ],
    requestHosts: [
      "static.hotjar.com",
      "hotjar.com",
    ],
    source: 'curated',
  },
  {
    id: "intercom",
    name: "Intercom",
    category: "functional",
    cookies: [
      { name: "intercom-id-", wildcard: true },
      { name: "intercom-session-", wildcard: true },
      { name: "intercom-device-id-", wildcard: true },
    ],
    localStorage: [
    ],
    requestHosts: [
      "widget.intercom.io",
      "intercom.io",
    ],
    source: 'curated',
  },
  {
    id: "hubspot",
    name: "HubSpot Analytics",
    category: "analytics",
    cookies: [
      { name: "hubspotutk", wildcard: false },
      { name: "__hstc", wildcard: false },
      { name: "__hssc", wildcard: false },
      { name: "__hssrc", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "hs-analytics.net",
      "hubspot.com",
      "hs-scripts.com",
    ],
    source: 'curated',
  },
  {
    id: "zendesk",
    name: "Zendesk Chat",
    category: "functional",
    cookies: [
      { name: "__zlcmid", wildcard: false },
      { name: "ZD-buid", wildcard: false },
      { name: "ZD-suid", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "static.zdassets.com",
      "zopim.com",
    ],
    source: 'curated',
  },
  {
    id: "crisp",
    name: "Crisp Chat",
    category: "functional",
    cookies: [
      { name: "crisp-client/session/", wildcard: true },
    ],
    localStorage: [
      { name: "crisp-client/session/", wildcard: true },
    ],
    requestHosts: [
      "client.crisp.chat",
      "crisp.chat",
    ],
    source: 'curated',
  },
  {
    id: "drift",
    name: "Drift",
    category: "functional",
    cookies: [
      { name: "driftt_aid", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "js.driftt.com",
      "drift.com",
    ],
    source: 'curated',
  },
  {
    id: "segment",
    name: "Segment",
    category: "analytics",
    cookies: [
      { name: "ajs_", wildcard: true },
    ],
    localStorage: [
      { name: "ajs_user_id", wildcard: false },
      { name: "ajs_anonymous_id", wildcard: false },
    ],
    requestHosts: [
      "cdn.segment.com",
      "segment.io",
    ],
    source: 'curated',
  },
  {
    id: "amplitude",
    name: "Amplitude",
    category: "analytics",
    cookies: [
      { name: "amplitude_id_", wildcard: true },
    ],
    localStorage: [
      { name: "amplitude_id_", wildcard: true },
      { name: "amplitude_unsent_", wildcard: true },
    ],
    requestHosts: [
      "cdn.amplitude.com",
      "api.amplitude.com",
    ],
    source: 'curated',
  },
  {
    id: "mixpanel",
    name: "Mixpanel",
    category: "analytics",
    cookies: [
    ],
    localStorage: [
    ],
    requestHosts: [
      "cdn.mxpnl.com",
      "api.mixpanel.com",
    ],
    source: 'curated',
  },
  {
    id: "twitter-pixel",
    name: "X (Twitter) Pixel",
    category: "marketing",
    cookies: [
      { name: "muc_ads", wildcard: false },
      { name: "_twitter_sess", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "static.ads-twitter.com",
      "analytics.twitter.com",
    ],
    source: 'curated',
  },
  {
    id: "clarity",
    name: "Microsoft Clarity",
    category: "analytics",
    cookies: [
      { name: "_clck", wildcard: false },
      { name: "_clsk", wildcard: false },
      { name: "CLID", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "clarity.ms",
    ],
    source: 'curated',
  },
  {
    id: "cloudflare-insights",
    name: "Cloudflare Web Analytics",
    category: "analytics",
    cookies: [
      { name: "_cflb", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "static.cloudflareinsights.com",
      "cloudflareinsights.com",
    ],
    source: 'curated',
  },
  {
    id: "vimeo",
    name: "Vimeo",
    category: "marketing",
    cookies: [
      { name: "vuid", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "player.vimeo.com",
      "vimeocdn.com",
    ],
    source: 'curated',
  },
  {
    id: "tiktok-pixel",
    name: "TikTok Pixel",
    category: "marketing",
    cookies: [
      { name: "_tt_enable_cookie", wildcard: false },
      { name: "_ttp", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "analytics.tiktok.com",
      "tiktok.com",
    ],
    source: 'curated',
  },
  {
    id: "recaptcha",
    name: "Google reCAPTCHA",
    category: "functional",
    cookies: [
      { name: "_GRECAPTCHA", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
    ],
    requestPaths: [
      "www.google.com/recaptcha/",
    ],
    google: true,
    source: 'curated',
  },
  {
    id: "google-ads",
    name: "Google Ads",
    category: "marketing",
    cookies: [
      { name: "_gcl_au", wildcard: false },
      { name: "_gcl_aw", wildcard: false },
      { name: "_gcl_dc", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "googleadservices.com",
      "googlesyndication.com",
    ],
    google: true,
    source: 'curated',
  },
  {
    id: "snapchat-pixel",
    name: "Snapchat Pixel",
    category: "marketing",
    cookies: [
      { name: "_scid", wildcard: false },
      { name: "_sctr", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "sc-analytics.appspot.com",
      "tr.snapchat.com",
      "static.ads.snapchat.com",
    ],
    source: 'curated',
  },
  {
    id: "pinterest-tag",
    name: "Pinterest Tag",
    category: "marketing",
    cookies: [
      { name: "_pinterest_ct_ua", wildcard: false },
      { name: "_pinterest_ct_la", wildcard: false },
      { name: "_epik", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "ct.pinterest.com",
      "s.pinimg.com",
    ],
    source: 'curated',
  },
  {
    id: "reddit-pixel",
    name: "Reddit Pixel",
    category: "marketing",
    cookies: [
      { name: "rdt_uuid", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "alb.reddit.com",
      "www.redditstatic.com",
    ],
    source: 'curated',
  },
  {
    id: "quora-pixel",
    name: "Quora Pixel",
    category: "marketing",
    cookies: [
      { name: "_qca", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "q.quora.com",
      "s.quora.com",
    ],
    source: 'curated',
  },
  {
    id: "posthog",
    name: "PostHog",
    category: "analytics",
    cookies: [
      { name: "ph_", wildcard: true },
    ],
    localStorage: [
      { name: "ph_", wildcard: true },
    ],
    requestHosts: [
      "app.posthog.com",
      "eu.posthog.com",
      "us.posthog.com",
    ],
    source: 'curated',
  },
  {
    id: "fullstory",
    name: "FullStory",
    category: "analytics",
    cookies: [
      { name: "fs_uid", wildcard: false },
      { name: "fs_lua", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "fullstory.com",
      "rs.fullstory.com",
      "edge.fullstory.com",
    ],
    source: 'curated',
  },
  {
    id: "heap",
    name: "Heap Analytics",
    category: "analytics",
    cookies: [
      { name: "_hp2_", wildcard: true },
      { name: "_hp2_id.", wildcard: true },
      { name: "_hp2_ses_props.", wildcard: true },
    ],
    localStorage: [
    ],
    requestHosts: [
      "cdn.heapanalytics.com",
      "heapanalytics.com",
    ],
    source: 'curated',
  },
  {
    id: "klaviyo",
    name: "Klaviyo",
    category: "marketing",
    cookies: [
      { name: "__kla_id", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "static.klaviyo.com",
      "a.klaviyo.com",
    ],
    source: 'curated',
  },
  {
    id: "mailchimp",
    name: "Mailchimp",
    category: "marketing",
    cookies: [
      { name: "_mc_", wildcard: true },
    ],
    localStorage: [
    ],
    requestHosts: [
      "chimpstatic.com",
      "list-manage.com",
    ],
    source: 'curated',
  },
  {
    id: "activecampaign",
    name: "ActiveCampaign",
    category: "marketing",
    cookies: [
      { name: "ac_enable_tracking", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "trackcmp.net",
      "tracker.activecampaign.com",
    ],
    source: 'curated',
  },
  {
    id: "braze",
    name: "Braze",
    category: "marketing",
    cookies: [
      { name: "ab.storage.userId.", wildcard: true },
      { name: "ab.storage.sessionId.", wildcard: true },
      { name: "ab.storage.deviceId.", wildcard: true },
    ],
    localStorage: [
      { name: "ab.storage.", wildcard: true },
    ],
    requestHosts: [
      "sdk.iad-01.braze.com",
      "sdk.iad-02.braze.com",
      "sdk.iad-03.braze.com",
      "sdk.fra-01.braze.eu",
      "sdk.fra-02.braze.eu",
    ],
    source: 'curated',
  },
  {
    id: "optimizely",
    name: "Optimizely",
    category: "analytics",
    cookies: [
      { name: "optimizelyBuckets", wildcard: false },
      { name: "optimizelyEndUserId", wildcard: false },
      { name: "optimizelyPendingLogEvents", wildcard: false },
    ],
    localStorage: [
      { name: "optimizely-", wildcard: true },
    ],
    requestHosts: [
      "cdn.optimizely.com",
      "optimizely.com",
      "logx.optimizely.com",
    ],
    source: 'curated',
  },
  {
    id: "vwo",
    name: "VWO (Visual Website Optimizer)",
    category: "analytics",
    cookies: [
      { name: "_vwo_uuid", wildcard: false },
      { name: "_vwo_uuid_v2", wildcard: false },
      { name: "_vwo_ds", wildcard: false },
      { name: "_vwo_", wildcard: true },
    ],
    localStorage: [
      { name: "_vwo_", wildcard: true },
    ],
    requestHosts: [
      "dev.visualwebsiteoptimizer.com",
      "dacdn.visualwebsiteoptimizer.com",
    ],
    source: 'curated',
  },
  {
    id: "lucky-orange",
    name: "Lucky Orange",
    category: "analytics",
    cookies: [
      { name: "_lo_uid", wildcard: false },
      { name: "_lo_v", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "d.luckyorange.com",
      "cdn.luckyorange.com",
    ],
    source: 'curated',
  },
  {
    id: "crazy-egg",
    name: "Crazy Egg",
    category: "analytics",
    cookies: [
      { name: "_ceir", wildcard: false },
      { name: "_ce.s", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "script.crazyegg.com",
      "crazyegg.com",
    ],
    source: 'curated',
  },
  {
    id: "mouseflow",
    name: "Mouseflow",
    category: "analytics",
    cookies: [
      { name: "_mf_id", wildcard: false },
      { name: "_mf_", wildcard: true },
    ],
    localStorage: [
    ],
    requestHosts: [
      "cdn.mouseflow.com",
      "mouseflow.com",
    ],
    source: 'curated',
  },
  {
    id: "freshchat",
    name: "Freshdesk / Freshchat",
    category: "functional",
    cookies: [
      { name: "_fc_", wildcard: true },
    ],
    localStorage: [
      { name: "freshchat_", wildcard: true },
    ],
    requestHosts: [
      "wchat.freshchat.com",
      "assetscdn.freshdesk.com",
    ],
    source: 'curated',
  },
  {
    id: "tidio",
    name: "Tidio",
    category: "functional",
    cookies: [
      { name: "tidio_", wildcard: true },
    ],
    localStorage: [
      { name: "tidio_", wildcard: true },
    ],
    requestHosts: [
      "widget.tidio.com",
    ],
    source: 'curated',
  },
  {
    id: "olark",
    name: "Olark",
    category: "functional",
    cookies: [
      { name: "hb_xid", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "static.olark.com",
      "olark.com",
    ],
    source: 'curated',
  },
  {
    id: "sentry",
    name: "Sentry",
    category: "functional",
    cookies: [
      { name: "__sentry_", wildcard: true },
    ],
    localStorage: [
      { name: "sentryReplaySession", wildcard: false },
      { name: "sentry-", wildcard: true },
    ],
    requestHosts: [
      "sentry.io",
    ],
    source: 'curated',
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "functional",
    cookies: [
      { name: "__stripe_mid", wildcard: false },
      { name: "__stripe_sid", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "js.stripe.com",
      "m.stripe.com",
      "q.stripe.com",
    ],
    source: 'curated',
  },
  {
    id: "cloudflare-turnstile",
    name: "Cloudflare Turnstile",
    category: "functional",
    cookies: [
    ],
    localStorage: [
      { name: "cf_turnstile_", wildcard: true },
    ],
    requestHosts: [
      "challenges.cloudflare.com",
    ],
    source: 'curated',
  },
  {
    id: "google-optimize",
    name: "Google Optimize (sunset)",
    category: "analytics",
    cookies: [
      { name: "_gaexp", wildcard: false },
      { name: "_opt_awcid", wildcard: false },
      { name: "_opt_utmc", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "optimize.google.com",
    ],
    google: true,
    source: 'curated',
  },
  {
    id: "plausible",
    name: "Plausible Analytics",
    category: "analytics",
    cookies: [
    ],
    localStorage: [
    ],
    requestHosts: [
      "plausible.io",
    ],
    source: 'curated',
  },
  {
    id: "fathom",
    name: "Fathom Analytics",
    category: "analytics",
    cookies: [
    ],
    localStorage: [
    ],
    requestHosts: [
      "cdn.usefathom.com",
      "usefathom.com",
    ],
    source: 'curated',
  },
  {
    id: "trustpilot",
    name: "Trustpilot Widget",
    category: "marketing",
    cookies: [
      { name: "eupubconsent-v2", wildcard: false },
    ],
    localStorage: [
    ],
    requestHosts: [
      "widget.trustpilot.com",
      "invitations-api.trustpilot.com",
    ],
    source: 'curated',
  },
  {
    id: "podium",
    name: "Podium",
    category: "functional",
    cookies: [
      { name: "podium_", wildcard: true },
    ],
    localStorage: [
    ],
    requestHosts: [
      "api.podium.com",
      "cdn.podium.com",
    ],
    source: 'curated',
  },
  {
    id: "pendo",
    name: "Pendo",
    category: "analytics",
    cookies: [
      { name: "_pendo_", wildcard: true },
    ],
    localStorage: [
      { name: "pendo_", wildcard: true },
    ],
    requestHosts: [
      "cdn.pendo.io",
      "data.pendo.io",
      "app.pendo.io",
    ],
    source: 'curated',
  },
]
