/**
 * Service fingerprint database for cookie/request classification.
 *
 * Sources:
 * 1. Open Cookie Database (github.com/jkwakman/Open-Cookie-Database)
 *    License: Apache-2.0 — compatible with this project's Apache-2.0 license.
 *    Attribution: Cookie data sourced from the Open Cookie Database by J. Kwakman
 *    (https://github.com/jkwakman/Open-Cookie-Database), licensed under Apache-2.0.
 *    Entries are generated at build time by `scripts/ingest-ocd.mjs` into
 *    `src/db-ocd.generated.ts`. To refresh: `node scripts/ingest-ocd.mjs`.
 *
 * 2. Hand-curated supplement — adds request-host matching and fills
 *    gaps not covered by the OCD (e.g. localStorage keys, iframe hosts).
 *    Source: data/services.yaml, compiled to src/db-curated.generated.ts by
 *    scripts/build-services-db.mjs. Run automatically via `prebuild`.
 *    The curated entries take precedence over OCD entries in lookup order
 *    (curated entries appear first in SERVICE_DB).
 *
 * Confidence levels:
 *   high   — two independent signals agree on the same service on the same page
 *            (e.g. a cookie match cross-checked against a fired requestHost).
 *            Computed in classifier.ts — lookup helpers never return 'high'.
 *   medium — single unambiguous signal (cookie match or host/request match,
 *            curated or OCD).
 *   low    — heuristic / declared-category only (no cookie or host signal)
 */

import { OCD_SERVICES } from './db-ocd.generated.js'
import { CURATED_SERVICES } from './db-curated.generated.js'

export type Confidence = 'high' | 'medium' | 'low'
export type ServiceCategory = 'necessary' | 'functional' | 'analytics' | 'marketing'

export interface CookiePattern {
  /** Exact cookie name, or a pattern ending in `*` for prefix matching. */
  name: string
  /** Whether `name` is a prefix wildcard (e.g. `_ga_*`). */
  wildcard: boolean
}

export interface ServiceDefinition {
  /** Unique stable identifier (slug). */
  id: string
  /** Human-readable name. */
  name: string
  /** Cookyay category this service belongs to. */
  category: ServiceCategory
  /** Cookie names / patterns. */
  cookies: CookiePattern[]
  /** localStorage key patterns. */
  localStorage: CookiePattern[]
  /** Request host substrings to match against `RequestRecord.host`. */
  requestHosts: string[]
  /** Source: 'ocd' = Open Cookie Database, 'curated' = hand-curated supplement. */
  source: 'ocd' | 'curated'
  /**
   * Host-qualified URL path prefixes for services that require path-level granularity.
   * Each entry is a `"host/path"` string, e.g. `"facebook.com/tr"` or
   * `"www.google.com/recaptcha/"`. A request matches if its host matches the entry's
   * host component (exact or subdomain) AND its pathname starts with the entry's path
   * component. This keeps path matching host-anchored — a `/tr`-prefixed path on an
   * unrelated host will NOT match meta-pixel.
   *
   * Use this for services whose request host is too broad to put in `requestHosts`
   * (e.g. `facebook.com` serves social login + pixel; `www.google.com` serves Maps,
   * Fonts, reCAPTCHA). The host+path combination is narrow enough to be unambiguous.
   *
   * @example `["facebook.com/tr", "www.google.com/recaptcha/"]`
   */
  requestPaths?: string[]
  /**
   * URL glob patterns for known script sources
   * (e.g. `"*.googletagmanager.com/gtm.js*"`).
   * Used to emit suggested script-blocking markup.
   */
  scriptUrlGlobs?: string[]
  /**
   * URL glob patterns for known embed (iframe) sources
   * (e.g. `"https://www.youtube.com/embed/*"`).
   * Used to emit suggested iframe-blocking markup.
   */
  iframeSrcGlobs?: string[]
}

// ---------------------------------------------------------------------------
// The combined database
// Order matters: entries listed earlier win on tie when two definitions match
// the same cookie (we prefer 'curated' entries which tend to be more specific).
//
// Curated entries: data/services.yaml → compiled by scripts/build-services-db.mjs
//                  → src/db-curated.generated.ts (git-committed, rebuilt in prebuild)
// OCD entries:     downloaded from Open Cookie Database → compiled by scripts/ingest-ocd.mjs
//                  → src/db-ocd.generated.ts (git-committed, rebuilt in prebuild)
// ---------------------------------------------------------------------------
export const SERVICE_DB: ServiceDefinition[] = [
  // -------------------------------------------------------------------------
  // CURATED entries (with request-host matching) — from data/services.yaml
  // -------------------------------------------------------------------------
  ...CURATED_SERVICES,

  // -------------------------------------------------------------------------
  // Open Cookie Database entries — generated by scripts/ingest-ocd.mjs
  // (Apache-2.0; see db-ocd.generated.ts for full attribution and entry count)
  // Curated entries above take precedence: findServiceByCookie() returns the
  // first match, and curated entries are listed first.
  // -------------------------------------------------------------------------
  ...OCD_SERVICES,
]

/** Schema version of the curated database (data/services.yaml). */
export const DB_SCHEMA_VERSION = 1

// ---------------------------------------------------------------------------
// Lookup helpers used by the classifier
// ---------------------------------------------------------------------------

/** Returns true if `cookieName` matches the given pattern (exact or prefix wildcard). */
export function matchesCookiePattern(pattern: CookiePattern, cookieName: string): boolean {
  if (pattern.wildcard) {
    return cookieName.startsWith(pattern.name)
  }
  return cookieName === pattern.name
}

/**
 * Find the best matching service for a given cookie name.
 * Returns { service, confidence: 'medium' } or null if not matched.
 *
 * Confidence returned here is always 'medium' — a single cookie signal is
 * unambiguous but not yet corroborated. The caller (classifier.ts) upgrades
 * to 'high' when a second independent signal (e.g. a requestHost match) is
 * observed for the same service on the same page.
 *
 * Lookup order: curated entries before OCD entries (SERVICE_DB is ordered),
 * so the first match is always the best match.
 */
export function findServiceByCookie(
  cookieName: string,
): { service: ServiceDefinition; confidence: Confidence } | null {
  for (const service of SERVICE_DB) {
    for (const pattern of service.cookies) {
      if (matchesCookiePattern(pattern, cookieName)) {
        return { service, confidence: 'medium' }
      }
    }
  }
  return null
}

/**
 * Find the best matching service for a request host.
 * Returns { service, confidence: 'medium' } or null.
 *
 * Matching rules (strictest first to avoid false positives):
 *   1. Exact match: host === h
 *   2. Subdomain match: host ends with ".<h>"
 *
 * The `includes()` check is intentionally NOT used — it produces false positives
 * (e.g. 't.co' in requestHosts would match 'react.com', 'giant.com', etc.).
 *
 * NOTE: This function only checks requestHosts, not requestPaths. It is safe to
 * use for scripts/iframes where only the hostname is available (no path context).
 * For full request URLs where path-level matching is needed, use findServiceByRequest().
 */
export function findServiceByHost(
  host: string,
): { service: ServiceDefinition; confidence: Confidence } | null {
  for (const service of SERVICE_DB) {
    for (const h of service.requestHosts) {
      if (host === h || host.endsWith(`.${h}`)) {
        return { service, confidence: 'medium' }
      }
    }
  }
  return null
}

/**
 * Find the best matching service for a third-party network request, applying
 * both host-level and path-level matching.
 *
 * **Semantics:** a request matches a service if EITHER condition holds:
 *
 *   1. **Host match:** the request's host matches a `requestHosts` entry
 *      (exact or subdomain — same rules as `findServiceByHost`).
 *      This handles unambiguous hosts like `connect.facebook.net`, `static.hotjar.com`.
 *
 *   2. **Host-qualified path match:** the request matches a `requestPaths` entry.
 *      Each `requestPaths` entry is a `"host/path"` string. The request matches
 *      if its host equals (or is a subdomain of) the entry's host component AND
 *      its pathname starts with the entry's path component. Both conditions must
 *      hold simultaneously — a `/tr`-prefixed path on an unrelated host does NOT
 *      match meta-pixel; `www.google.com/maps/...` does NOT match reCAPTCHA.
 *      This handles services whose host alone would produce false positives
 *      (e.g. `facebook.com/tr` for Meta Pixel, `www.google.com/recaptcha/` for reCAPTCHA).
 *
 * **Path semantics:** prefix match — `"www.google.com/recaptcha/"` matches
 * `www.google.com/recaptcha/api.js`, `www.google.com/recaptcha/enterprise.js`, etc.
 * Consistent with how the architecture describes these as "path prefixes"
 * [architecture.md §Amendments 2026-06-10 — change 1].
 *
 * **Authoring guidance (services.yaml):**
 * - Put unambiguous host entries in `requestHosts` (match by host, no path needed).
 * - For hosts shared with unrelated traffic (e.g. `facebook.com`, `www.google.com`),
 *   leave those hosts OUT of `requestHosts` and instead add the distinctive
 *   `"host/path"` pattern to `requestPaths`.
 *
 * @param url  The full request URL string (e.g. "https://www.facebook.com/tr?id=123").
 * @param host The pre-extracted hostname (e.g. "www.facebook.com"). Passed separately
 *             so callers don't pay double-parse cost.
 */
export function findServiceByRequest(
  url: string,
  host: string,
): { service: ServiceDefinition; confidence: Confidence } | null {
  // Parse pathname once, outside the service loop.
  let pathname: string | null = null
  try {
    pathname = new URL(url).pathname
  } catch {
    // Malformed URL — fall back to host-only matching (no path check possible).
  }

  for (const service of SERVICE_DB) {
    // Condition 1: host match (same as findServiceByHost)
    for (const h of service.requestHosts) {
      if (host === h || host.endsWith(`.${h}`)) {
        return { service, confidence: 'medium' }
      }
    }

    // Condition 2: host-qualified path match.
    // Each requestPaths entry is "host/path" — both must match simultaneously.
    // A path prefix on an unrelated host does NOT match (prevents false positives).
    if (pathname !== null && service.requestPaths && service.requestPaths.length > 0) {
      for (const entry of service.requestPaths) {
        const slashIdx = entry.indexOf('/')
        if (slashIdx === -1) continue // malformed entry — skip
        const entryHost = entry.slice(0, slashIdx)
        const entryPath = entry.slice(slashIdx) // includes the leading '/'
        const hostMatches = host === entryHost || host.endsWith(`.${entryHost}`)
        if (hostMatches && pathname.startsWith(entryPath)) {
          return { service, confidence: 'medium' }
        }
      }
    }
  }
  return null
}

/**
 * Find the best matching service for a localStorage key.
 * Returns { service, confidence: 'medium' } or null if not matched.
 *
 * Confidence is always 'medium' here — single-signal. Upgrade to 'high'
 * happens in classifier.ts when a second independent signal is also observed.
 */
export function findServiceByLocalStorage(
  key: string,
): { service: ServiceDefinition; confidence: Confidence } | null {
  for (const service of SERVICE_DB) {
    for (const pattern of service.localStorage) {
      if (matchesCookiePattern(pattern, key)) {
        return { service, confidence: 'medium' }
      }
    }
  }
  return null
}
