/**
 * AUTO-GENERATED by packages/scanner/scripts/build-services-db.mjs — DO NOT EDIT MANUALLY.
 * Generated: 2026-06-11
 * Source: packages/scanner/data/services.yaml (schemaVersion: 1)
 *
 * Client-safe slice of the curated service DB for runtime auto-block (v5).
 * Contains ONLY: id, category, requestHosts, requestPaths, scriptUrlGlobs,
 * iframeSrcGlobs, and google flag. Cookies/localStorage/source are stripped.
 *
 * Services with google:true are owned by Google (GA4/GTM/Google Ads/etc.) and
 * are handled by Consent Mode v2 instead of DOM-blocking.
 * [goals.md §Consent Mode v2: skip Google tags, prd.md §3.4]
 *
 * To regenerate: node packages/scanner/scripts/build-services-db.mjs
 * (or: pnpm --filter @cookyay/scanner build, or the cookyay prebuild)
 */
import type { AutoBlockEntry } from './db-autoblock.types.js'

// 50 curated services with client-side signals
// (6 Google-owned [skipped by runtime matcher], 44 non-Google [actively blocked])
export const AUTOBLOCK_SERVICES: AutoBlockEntry[] = [
  {
    id: "ga4",
    category: "analytics",
    google: true,
    requestHosts: [
      "google-analytics.com",
      "analytics.google.com",
      "googletagmanager.com",
    ],
  },
  {
    id: "ua",
    category: "analytics",
    google: true,
    requestHosts: [
      "google-analytics.com",
    ],
  },
  {
    id: "gtm",
    category: "analytics",
    google: true,
    requestHosts: [
      "googletagmanager.com",
    ],
  },
  {
    id: "meta-pixel",
    category: "marketing",
    requestHosts: [
      "connect.facebook.net",
    ],
    requestPaths: [
      "facebook.com/tr",
    ],
  },
  {
    id: "youtube",
    category: "marketing",
    requestHosts: [
      "youtube.com",
      "youtube-nocookie.com",
      "ytimg.com",
    ],
  },
  {
    id: "linkedin-insight",
    category: "marketing",
    requestHosts: [
      "linkedin.com",
      "snap.licdn.com",
    ],
  },
  {
    id: "hotjar",
    category: "analytics",
    requestHosts: [
      "static.hotjar.com",
      "hotjar.com",
    ],
  },
  {
    id: "intercom",
    category: "functional",
    requestHosts: [
      "widget.intercom.io",
      "intercom.io",
    ],
  },
  {
    id: "hubspot",
    category: "analytics",
    requestHosts: [
      "hs-analytics.net",
      "hubspot.com",
      "hs-scripts.com",
    ],
  },
  {
    id: "zendesk",
    category: "functional",
    requestHosts: [
      "static.zdassets.com",
      "zopim.com",
    ],
  },
  {
    id: "crisp",
    category: "functional",
    requestHosts: [
      "client.crisp.chat",
      "crisp.chat",
    ],
  },
  {
    id: "drift",
    category: "functional",
    requestHosts: [
      "js.driftt.com",
      "drift.com",
    ],
  },
  {
    id: "segment",
    category: "analytics",
    requestHosts: [
      "cdn.segment.com",
      "segment.io",
    ],
  },
  {
    id: "amplitude",
    category: "analytics",
    requestHosts: [
      "cdn.amplitude.com",
      "api.amplitude.com",
    ],
  },
  {
    id: "mixpanel",
    category: "analytics",
    requestHosts: [
      "cdn.mxpnl.com",
      "api.mixpanel.com",
    ],
  },
  {
    id: "twitter-pixel",
    category: "marketing",
    requestHosts: [
      "static.ads-twitter.com",
      "analytics.twitter.com",
    ],
  },
  {
    id: "clarity",
    category: "analytics",
    requestHosts: [
      "clarity.ms",
    ],
  },
  {
    id: "cloudflare-insights",
    category: "analytics",
    requestHosts: [
      "static.cloudflareinsights.com",
      "cloudflareinsights.com",
    ],
  },
  {
    id: "vimeo",
    category: "marketing",
    requestHosts: [
      "player.vimeo.com",
      "vimeocdn.com",
    ],
  },
  {
    id: "tiktok-pixel",
    category: "marketing",
    requestHosts: [
      "analytics.tiktok.com",
      "tiktok.com",
    ],
  },
  {
    id: "recaptcha",
    category: "functional",
    google: true,
    requestHosts: [
    ],
    requestPaths: [
      "www.google.com/recaptcha/",
    ],
  },
  {
    id: "google-ads",
    category: "marketing",
    google: true,
    requestHosts: [
      "googleadservices.com",
      "googlesyndication.com",
    ],
  },
  {
    id: "snapchat-pixel",
    category: "marketing",
    requestHosts: [
      "sc-analytics.appspot.com",
      "tr.snapchat.com",
      "static.ads.snapchat.com",
    ],
  },
  {
    id: "pinterest-tag",
    category: "marketing",
    requestHosts: [
      "ct.pinterest.com",
      "s.pinimg.com",
    ],
  },
  {
    id: "reddit-pixel",
    category: "marketing",
    requestHosts: [
      "alb.reddit.com",
      "www.redditstatic.com",
    ],
  },
  {
    id: "quora-pixel",
    category: "marketing",
    requestHosts: [
      "q.quora.com",
      "s.quora.com",
    ],
  },
  {
    id: "posthog",
    category: "analytics",
    requestHosts: [
      "app.posthog.com",
      "eu.posthog.com",
      "us.posthog.com",
    ],
  },
  {
    id: "fullstory",
    category: "analytics",
    requestHosts: [
      "fullstory.com",
      "rs.fullstory.com",
      "edge.fullstory.com",
    ],
  },
  {
    id: "heap",
    category: "analytics",
    requestHosts: [
      "cdn.heapanalytics.com",
      "heapanalytics.com",
    ],
  },
  {
    id: "klaviyo",
    category: "marketing",
    requestHosts: [
      "static.klaviyo.com",
      "a.klaviyo.com",
    ],
  },
  {
    id: "mailchimp",
    category: "marketing",
    requestHosts: [
      "chimpstatic.com",
      "list-manage.com",
    ],
  },
  {
    id: "activecampaign",
    category: "marketing",
    requestHosts: [
      "trackcmp.net",
      "tracker.activecampaign.com",
    ],
  },
  {
    id: "braze",
    category: "marketing",
    requestHosts: [
      "sdk.iad-01.braze.com",
      "sdk.iad-02.braze.com",
      "sdk.iad-03.braze.com",
      "sdk.fra-01.braze.eu",
      "sdk.fra-02.braze.eu",
    ],
  },
  {
    id: "optimizely",
    category: "analytics",
    requestHosts: [
      "cdn.optimizely.com",
      "optimizely.com",
      "logx.optimizely.com",
    ],
  },
  {
    id: "vwo",
    category: "analytics",
    requestHosts: [
      "dev.visualwebsiteoptimizer.com",
      "dacdn.visualwebsiteoptimizer.com",
    ],
  },
  {
    id: "lucky-orange",
    category: "analytics",
    requestHosts: [
      "d.luckyorange.com",
      "cdn.luckyorange.com",
    ],
  },
  {
    id: "crazy-egg",
    category: "analytics",
    requestHosts: [
      "script.crazyegg.com",
      "crazyegg.com",
    ],
  },
  {
    id: "mouseflow",
    category: "analytics",
    requestHosts: [
      "cdn.mouseflow.com",
      "mouseflow.com",
    ],
  },
  {
    id: "freshchat",
    category: "functional",
    requestHosts: [
      "wchat.freshchat.com",
      "assetscdn.freshdesk.com",
    ],
  },
  {
    id: "tidio",
    category: "functional",
    requestHosts: [
      "widget.tidio.com",
    ],
  },
  {
    id: "olark",
    category: "functional",
    requestHosts: [
      "static.olark.com",
      "olark.com",
    ],
  },
  {
    id: "sentry",
    category: "functional",
    requestHosts: [
      "sentry.io",
    ],
  },
  {
    id: "stripe",
    category: "functional",
    requestHosts: [
      "js.stripe.com",
      "m.stripe.com",
      "q.stripe.com",
    ],
  },
  {
    id: "cloudflare-turnstile",
    category: "functional",
    requestHosts: [
      "challenges.cloudflare.com",
    ],
  },
  {
    id: "google-optimize",
    category: "analytics",
    google: true,
    requestHosts: [
      "optimize.google.com",
    ],
  },
  {
    id: "plausible",
    category: "analytics",
    requestHosts: [
      "plausible.io",
    ],
  },
  {
    id: "fathom",
    category: "analytics",
    requestHosts: [
      "cdn.usefathom.com",
      "usefathom.com",
    ],
  },
  {
    id: "trustpilot",
    category: "marketing",
    requestHosts: [
      "widget.trustpilot.com",
      "invitations-api.trustpilot.com",
    ],
  },
  {
    id: "podium",
    category: "functional",
    requestHosts: [
      "api.podium.com",
      "cdn.podium.com",
    ],
  },
  {
    id: "pendo",
    category: "analytics",
    requestHosts: [
      "cdn.pendo.io",
      "data.pendo.io",
      "app.pendo.io",
    ],
  },
]
